### ISSUE TITLE
Complete for profiles doesn't work

### ISSUE THREAD

**Issue by Hunsu** [jschneider/fish-maven-completion#1]
I defined a profile in my pom but when I do:

```
mvn install -P
```

I don't get the completion for my profile.

**Comment by jschneider** [comment]
Well. It should work. Could you maybe provide an example?

**Comment by Hunsu** [comment]
It doesn't work with the pom below or maybe it's me who don't know how to use it.

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

```
<modelVersion>4.0.0</modelVersion>


<artifactId>xxxxxx</artifactId>
<version>0.0.8-SNAPSHOT</version>
<packaging>war</packaging>

<properties>
    <exclude.tests>nothing-to-exclude</exclude.tests>
</properties>

<dependencies>
    <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-math3</artifactId>
        <version>3.5</version>
    </dependency>
    <dependency>
        <groupId>org.reflections</groupId>
        <artifactId>reflections</artifactId>
        <version>0.9.10</version>
        <scope>test</scope>
    </dependency>

</dependencies>
<profiles>
    <profile>
        <id>fast</id>
        <properties>
            <exclude.tests>**/xxx/**/*.java</exclude.tests>
        </properties>
    </profile>
</profiles>
```

</project>

**Comment by jschneider** [comment]
Hey, gave it a shot. Seems to work for me.

One thing: Did you add a space after the "-P"? This is necessary for me.

**Comment by Hunsu** [comment]
Thanks it works when adding a space after "-P".
